apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: c1-cluster-create
spec:
  destination:
    name: ''
    namespace: ''
    server: 'https://kubernetes.default.svc'
  source:
    path: argo/clusterApi/mgmt
    repoURL: 'https://github.com/iemkamran/opensource.git'
    targetRevision: HEAD
    helm:
      valueFiles:
        - values-c1.yaml
  project: default